FROM alpine:3.22.2 AS builder

# Build-Tools installieren
RUN apk add --no-cache \
    go \
    nodejs \
    npm \
    git \
    make

RUN npm install -g pnpm

WORKDIR /app

RUN git clone https://github.com/MarinX/agewasm.git .

RUN pnpm install

RUN make import build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
