FROM alpine:3.23.0 AS builder

# Build-Tools installieren
RUN apk add --no-cache \
    go \
    nodejs \
    npm \
    git \
    make

RUN npm install -g pnpm

WORKDIR /app

RUN git clone https://github.com/MarinX/agewasm.git .

RUN pnpm install

RUN make import build

FROM nginxinc/nginx-unprivileged:alpine3.23-perl

USER root

RUN apk update && apk upgrade --no-cache

USER nginx

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
